notifications:
  email:
    on_success: always
    on_failure: always

os: linux
sudo: required
jdk:
  - "openjdk11"
git:
  depth: false

env:
  PROJECT_MAJOR_VERSION=1
  PROJECT_MINOR_VERSION=0

branches:
  only:
    - /^feature\/QSA-[0-9]+/
    - master

before_install:
  - chmod +x gradlew
  - chmod +x ./support/pipeline/pipeline.sh
script:
  - ./support/pipeline/pipeline.sh
