version: 2.1
orbs:
  jira: circleci/jira@1.3.1

commands:
  set_local_environment:
    steps:
      - run:
          name: Environment Setup
          command: |
            export BRANCH_NAME=${CIRCLE_BRANCH}
            if [[ "${BRANCH_NAME}" != "master" ]]; then
              BRANCH_NAME=$(echo "${BRANCH_NAME}" | sed s#/#-#g | sed s/[.]/_/g | sed s#-#_#g | awk '{print $1""}') || exit
            fi
            RELEASE_VERSION=${PROJECT_MAJOR_VERSION}.${PROJECT_MINOR_VERSION}.${CIRCLE_BUILD_NUM}
            if [[ "${BRANCH_NAME}" != "master" ]]; then
              RELEASE_VERSION="${RELEASE_VERSION}_${BRANCH_NAME}"
            fi
            echo "BRANCH_NAME" "${BRANCH_NAME}"
            echo "RELEASE_VERSION" "${RELEASE_VERSION}"
            echo "export BRANCH_NAME=${BRANCH_NAME}" >> "$BASH_ENV"
            echo "export RELEASE_VERSION=${RELEASE_VERSION}" >> "$BASH_ENV"
            mkdir -p envs 
            echo "${RELEASE_VERSION}" > envs/release-version
            chmod +x gradlew
  deploy:
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Environment Setup
          command: |
            RELEASE_VERSION=$(cat envs/release-version)
            echo "export RELEASE_VERSION=${RELEASE_VERSION}" >> "$BASH_ENV"
            
            echo "export CONTAINER_NAME=${QSA_ENVIRONMENT}-qsa-calculator" >> "$BASH_ENV"
            echo "export IMAGE_NAME=docker.pkg.github.com/queueing-systems-assistance/qsa-calculator/qsa-calculator" >> "$BASH_ENV"

      - run:
          name: Pull Image
          command: |
            curl --request POST \
              --url "${ENDPOINT}/images/create?fromImage=${IMAGE_NAME}&tag=${RELEASE_VERSION}" \
              --header "X-API-Key: ${PTR_TOKEN}" \
              --header "X-Registry-Auth: ${DCR_TOKEN}" \
              --header "${HEADER_CONTENT_TYPE}" \
              --fail \
              --show-error
      - run:
          name: Stop Container
          command: |
            curl --request POST \
              --url "${ENDPOINT}/containers/${CONTAINER_NAME}/stop" \
              --header "X-API-Key: ${PTR_TOKEN}" \
              --header "${HEADER_CONTENT_TYPE}"
      - run:
          name: Remove Container
          command: |
            curl --request DELETE \
              --url "${ENDPOINT}/containers/${CONTAINER_NAME}" \
              --header "X-API-Key: ${PTR_TOKEN}" \
              --header "${HEADER_CONTENT_TYPE}"
      - run:
          name: Create Container
          command: |
            UPDATED_ENV_NAME=$(echo "${QSA_ENVIRONMENT}" | tr :a-z :A-Z:)
            JAVA_ARGS_ENV_NAME=JAVA_JVM_ARGS_$UPDATED_ENV_NAME
            IP_ADDRESS_NAME=IP_ADDRESS_$UPDATED_ENV_NAME
            ADDITIONAL_CONFIG="{\"HostConfig\":{\"RestartPolicy\":{\"Name\":\"always\"}},\"Env\":[\"JAVA_JVM_ARGS=${!JAVA_ARGS_ENV_NAME}\"],\"Image\":\"${IMAGE_NAME}:${RELEASE_VERSION}\",\"NetworkingConfig\":{\"EndpointsConfig\":{\"${NETWORK}\":{\"IPAMConfig\":{\"IPv4Address\":\"${!IP_ADDRESS_NAME}\"}}}}}"
            curl --request POST \
              --url "${ENDPOINT}/containers/create?name=${CONTAINER_NAME}" \
              --header "X-API-Key: ${PTR_TOKEN}" \
              --header "${HEADER_CONTENT_TYPE}" \
              --data "${ADDITIONAL_CONFIG}" \
              --fail \
              --show-error
      - run:
          name: Start Container
          command: |
            curl --request POST \
              --url "${ENDPOINT}/containers/${CONTAINER_NAME}/start" \
              --header "X-API-Key: ${PTR_TOKEN}" \
              --header "${HEADER_CONTENT_TYPE}" \
              --data " " \
              --fail \
              --show-error
jobs:
  build:
    environment:
      PROJECT_MAJOR_VERSION: 1
      PROJECT_MINOR_VERSION: 1
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - set_local_environment
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Checkstyle validation
          command: |
            ./gradlew checkstyleMain checkstyleTest -Prelease.version="${RELEASE_VERSION}"
      - run:
          name: Running Tests
          command: |
            ./gradlew test -Prelease.version="${RELEASE_VERSION}"
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: |
            ./gradlew -x test -x checkstyleMain -x checkstyleTest build -Prelease.version="${RELEASE_VERSION}"
      - setup_remote_docker
      - run:
          name: Docker
          command: |
            echo "${DOCKER_GITHUB_PASSWORD}" | docker login docker.pkg.github.com -u "${DOCKER_GITHUB_USERNAME}" --password-stdin
            docker build \
              -f ./support/docker/Dockerfile \
              -t docker.pkg.github.com/queueing-systems-assistance/qsa-calculator/qsa-calculator:"${RELEASE_VERSION}" .
            docker push docker.pkg.github.com/queueing-systems-assistance/qsa-calculator/qsa-calculator:"${RELEASE_VERSION}"
      - persist_to_workspace:
          root: .
          paths:
            - envs/release-version
      - run:
          name: Git Tagging
          command: |
            git config --global user.email "builds@circle-ci.com"
            git config --global user.name "Circle CI"
            git tag -a -f "${RELEASE_VERSION}" -m "${RELEASE_VERSION}"
            git push -f "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" refs/tags/"${RELEASE_VERSION}"
  deploy-lab:
    docker:
      - image: cimg/base:2022.01
    environment:
      QSA_ENVIRONMENT: lab
    steps:
      - deploy
  deploy-prod:
    docker:
      - image: cimg/base:2022.01
    environment:
      QSA_ENVIRONMENT: prod
    steps:
      - deploy
workflows:
  version: 2
  default-pipeline:
    jobs:
      - build:
          context:
            - Secrets
          filters:
            branches:
              only:
                - /^master/
                - /^feature\/QSA-[0-9]+/
          post-steps:
            - jira/notify:
                scan_commit_body: true
                job_type: build
                token_name: CIRCLE_CI_ARTIFACTS
      - deploy-hold-lab:
          requires:
            - build
          type: approval
      - deploy-lab:
          requires:
            - deploy-hold-lab
          context:
            - Secrets
          filters:
            branches:
              only:
                - /^master/
                - /^feature\/QSA-[0-9]+/
          post-steps:
            - jira/notify:
                scan_commit_body: true
                job_type: deployment
                environment_type: staging
                token_name: CIRCLE_CI_ARTIFACTS
      - deploy-hold-prod:
          requires:
            - deploy-lab
          type: approval
          filters:
            branches:
              only:
                - /^master/
      - deploy-prod:
          requires:
            - deploy-hold-prod
          context:
            - Secrets
          filters:
            branches:
              only:
                - /^master/
          post-steps:
            - jira/notify:
                scan_commit_body: true
                job_type: deployment
                environment_type: production
                token_name: CIRCLE_CI_ARTIFACTS