version: 2
jobs:
  build:
    machine: true
    environment:
      PROJECT_MAJOR_VERSION: 1
      PROJECT_MINOR_VERSION: 1
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Default
          command: |
            chmod +x gradlew
            chmod +x ./support/pipeline/pipeline.sh
            ./support/pipeline/pipeline.sh
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - ^master
                - ^feature\/QSA-[0-9]+

