# Spring Metrics
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,heatlh,metrics
  metrics:
    export:
      # Replace the url, username and password if you want to use the metrics and enable the feature
      elastic:
        enabled: false
        step: 1m
        index: qsa.${spring.application.name}.${spring.profiles.active}
        host: http://localhost:9200
        user-name:
        password:
  endpoint:
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true

# Spring Application
spring:
  main:
    banner-mode: "off"
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      load-on-startup: 1
  application:
    name: calculator
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
    locale-resolver: accept_header

# Config Packs
qsa:
  config:
    uris: https://qsa.inf.unideb.hu/default/api/config/system, https://qsa.inf.unideb.hu/default/api/config/feature
    refresh-rate-in-minutes: 60
