
# POD Name
kubernetes:
  pod-name: dev

management:
  # Spring Actuator
  endpoints:
    web:
      exposure:
        include: info, health
  # Graphite
  metrics:
    export:
      graphite:
        port: 2003
        host: localhost
        tags-as-prefix: QSA.${spring.profiles.active}.${kubernetes.pod-name}
        enabled: false
        duration-units: "seconds"
        step: 5
  # Geo
  geo:
    enabled: false
    maxmind:
      path: resources/maxmind.mmdb

# Spring Application
spring:
  main:
    banner-mode: "off"
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: true
    servlet:
      load-on-startup: 1
  resources:
    add-mappings: false
  application:
    name: QSA
  profiles:
    active: dev

# Logging
logging:
  config: classpath:logback-dev.xml
  port: 9500
  host: localhost
  url: http://${logging.host}:${logging.port}

# Config Packs
qsa:
  config:
    uris:
      #- https://qsa.inf.unideb.hu/default/api/config/system
      - C:\Users\kcsan\Dev\QSA\qsa-system-config-pack
      #- https://qsa.inf.unideb.hu/default/api/config/feature
      - C:\Users\kcsan\Dev\QSA\qsa-feature-config-pack
